### ISSUE TITLE
Two mis-rotated item boxes in Act 3

### ISSUE THREAD

**Issue by cheatfreak47** [ItsEasyActually/AutoDemo_WindyValley#1]
Found what appears to be two item boxes in Act 3 that are mis-rotated in the little valley area right before the end capsule. Probably only happens with SADXFE since that re-enables capsule rotation features. Probably.

![71250_20181109030353_1](https://user-images.githubusercontent.com/7818664/48250438-4aa59800-e3cc-11e8-962c-095a1b85611c.png)
Probably a quick fix, right?

**Comment by ItsEasyActually** [comment]
Ah, thanks for sharing! Yeah, this is a relatively quick fix. Unfortunately we won't be posting any further updates until after SHC is over (towards the end of the month), but we will have these fixed in that first update. We will hopefully fix a few other things by then as well.

**Comment by cheatfreak47** [comment]
Neat, and good luck in the contest! I'll definitely be voting for ya.

**Comment by cheatfreak47** [comment]
fixed in release 1.05, commit c83a519b
