### ISSUE TITLE
Small Camera tweak in Act 2

### ISSUE THREAD

**Issue by cheatfreak47** [ItsEasyActually/AutoDemo_WindyValley#2]
Full disclosure, I have no bloody clue how the camera works, but I do have an eye for game design and I found something that is pretty tough and it's definitely the camera's fault.

It's tough to describe what I mean but basically the shortest way through the tornado section is really hard to pull off due to the camera not really doing a good job of showing where the player needs to move to land at a certain point.

I recorded an animated gif to demonstrate and you'll see at one point I miss a platform because I don't know where to land. That's basically the problem, if there's some way to make the camera pan so you can see that platform with the flat spring on it, that'd be considerably better.

![GyfcatVideo](https://giant.gfycat.com/AllFriendlyChimneyswift.gif)

If this isn't possible to fix, it's all good, just providing some general feedback as I continue to play this mod in my free time.

**Comment by supercoolsonic** [comment]
I'm happy to say this has been mostly fixed. The camera now offers a much better angle when accessing that platform from below. As with the previous fix, this won't be released until the contest is over, however. Thank you for reporting this!

**Comment by cheatfreak47** [comment]
Fixed in release 1.05, commit 87fda1ee
